apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  # We will deploy to the 'default' namespace, but you can change this
  namespace: default
  labels:
    app: my-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app # This label is KEY for finding logs in Loki
    spec:
      containers:
        - name: java-container
          image: my-java-app:v1
          imagePullPolicy: IfNotPresent # Uses local image if available
          ports:
            - containerPort: 8080 # Change to your app's port
